### ISSUE TITLE
 core._resourcesStateChange is not a function (in core.js)

### ISSUE THREAD

**Issue by wmhartl** [JiHong88/suneditor#1217]
Hi @JiHong88 thank you for your efforts. From your note on [issue 1191](https://github.com/JiHong88/suneditor/issues/1191), after updating to 2.44.4 (and even to 2.44.8), we're still seeing this:

```
core.js:6229 Uncaught TypeError: this._resourcesStateChange is not a function
    at Object.<anonymous> (core.js:6229:22)
```

Would perhaps checking the value using typeof solve the issue? Something like I see you doing elsewhere in core.js:
`if (typeof this._resourcesStateChange === "function") this._resourcesStateChange();`

Happy to test out possible solutions if it would be helpful for you.

(I found a thread for this on the suneditor-react side that might be of interest also: https://github.com/mkhstar/suneditor-react/issues/296)

**Comment by JiHong88** [comment]
Yes, it seems to be solved with "typeof".

**Comment by JiHong88** [comment]
The [2.44.9](https://github.com/JiHong88/suneditor/releases/tag/2.44.9) version has been updated.
Thank you.
